server:
  port: 8091

spring:
  application:
    name: sharding-proxy-demo
  cloud:
    nacos:
      discovery:
        # 配置 nacos 地址
        server-addr: 192.168.1.11:8848
      config:
        server-addr: 192.168.1.11:8848
        # 设置配置文件前缀，默认为 ${spring.application.name}
        prefix: ${spring.application.name}
  datasource:
    # 配置数据源类型
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/sharding_user2?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://localhost:3306/t_user_0?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    username: root
    password: root
#    # 初始化，最小，最大连接数
#    initialSize: 3
#    minidle: 3
#    maxActive: 18
#    # 获取数据库连接等待的超时时间
#    maxWait: 60000
#    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
#    timeBetweenEvictionRunsMillis: 60000
#    validationQuery: SELECT 1 FROM dual
#    # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
#    filters: stat,wall,log4j